export const orderFormResponse = {
  id: '582a80ca9cb64c0a89a46097793c6389',
  items: [
    {
      additionalInfo: {
        brandName: 'Marca',
      },
      attachments: [],
      attachmentOfferings: [],
      bundleItems: [],
      parentAssemblyBinding: null,
      parentItemIndex: null,
      sellingPriceWithAssemblies: null,
      options: null,
      availability: 'available',
      detailUrl: '/navel-oranges-grown-large-fresh-fruit/p',
      id: '4',
      imageUrls: {
        at1x: '//gabrielhosino.vteximg.com.br/arquivos/ids/155397-96-auto',
        at2x: '//gabrielhosino.vteximg.com.br/arquivos/ids/155397-192-auto',
        at3x: '//gabrielhosino.vteximg.com.br/arquivos/ids/155397-288-auto',
      },
      listPrice: 10000,
      manualPrice: null,
      measurementUnit: 'un',
      name: 'Laranjas de umbigo cultivadas com frutas frescas grandes',
      offerings: [],
      price: 10000,
      priceTags: [],
      productCategories: {
        '9282': 'Food and beverage',
      },
      productCategoryIds: '/9282/',
      productRefId: '880032',
      productId: '7',
      quantity: 1,
      seller: '1',
      sellingPrice: 10000,
      skuName: 'Pacote de 1',
      skuSpecifications: [],
      unitMultiplier: 1,
      uniqueId: '213150163D0B421F90A59A327EC8DC10',
      refId: '880320a',
      isGift: false,
    },
  ],
  canEditData: true,
  loggedIn: false,
  userProfileId: null,
  userType: 'STORE_USER',
  marketingData: {
    coupon: '',
    utmCampaign: '',
    utmMedium: '',
    utmSource: '',
    utmiCampaign: '',
    utmiPart: '',
    utmiPage: '',
  },
  totalizers: [
    {
      id: 'Items',
      name: 'Total dos Itens',
      value: 10000,
    },
  ],
  shipping: {
    countries: ['BRA', 'USA'],
    availableAddresses: [],
    selectedAddress: null,
    deliveryOptions: [],
    pickupOptions: [],
    isValid: false,
  },
  paymentData: {
    paymentSystems: [
      {
        id: '2',
        name: 'Visa',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^4[0-9]{15}$',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '2',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2021-10-08T13:03:06.9660328Z',
      },
    ],
    payments: [],
    installmentOptions: [
      {
        paymentSystem: '2',
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 10000,
            total: 10000,
          },
        ],
      },
    ],
    availableAccounts: [],
    isValid: false,
  },
  clientProfileData: null,
  clientPreferencesData: {
    locale: 'pt-BR',
    optInNewsletter: null,
  },
  messages: {
    couponMessages: [],
    generalMessages: [],
  },
  value: 10000,
  allowManualPrice: false,
}
