declare module '@vtex/styleguide/lib/Card'
declare module '@vtex/styleguide/lib/Input'
declare module '@vtex/styleguide/lib/Button'
declare module '@vtex/styleguide/lib/Box'
declare module '@vtex/styleguide/lib/ToastProvider'
